/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    '/': {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        /**
         * Корневой эндпоинт API
         * @description Возвращает plain text (приветствие или статус).
         */
        get: {
            parameters: {
                query?: never
                header?: never
                path?: never
                cookie?: never
            }
            requestBody?: never
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown
                    }
                    content: {
                        'text/plain': string
                    }
                }
                500: components['responses']['ApiError500']
            }
        }
        put?: never
        post?: never
        delete?: never
        options?: never
        head?: never
        patch?: never
        trace?: never
    }
    '/auth/register': {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        get?: never
        put?: never
        /**
         * Регистрация пользователя
         * @description После успешной регистрации на email пользователя отправляется письмо со ссылкой для подтверждения (см. POST /auth/confirm-email).
         */
        post: {
            parameters: {
                query?: never
                header?: never
                path?: never
                cookie?: never
            }
            requestBody: {
                content: {
                    'application/json': components['schemas']['AuthRegisterRequest']
                }
            }
            responses: {
                /** @description Пользователь создан, возвращаются токены и данные пользователя */
                201: {
                    headers: {
                        [name: string]: unknown
                    }
                    content: {
                        'application/json': components['schemas']['AuthRegisterResponse']
                    }
                }
                400: components['responses']['ApiError400']
                409: components['responses']['ApiError409']
                500: components['responses']['ApiError500']
            }
        }
        delete?: never
        options?: never
        head?: never
        patch?: never
        trace?: never
    }
    '/auth/login': {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        get?: never
        put?: never
        /** Вход по email и паролю */
        post: {
            parameters: {
                query?: never
                header?: never
                path?: never
                cookie?: never
            }
            requestBody: {
                content: {
                    'application/json': components['schemas']['AuthLoginRequest']
                }
            }
            responses: {
                /** @description Успешный вход */
                200: {
                    headers: {
                        [name: string]: unknown
                    }
                    content: {
                        'application/json': components['schemas']['AuthLoginResponse']
                    }
                }
                400: components['responses']['ApiError400']
                401: components['responses']['ApiError401']
                500: components['responses']['ApiError500']
            }
        }
        delete?: never
        options?: never
        head?: never
        patch?: never
        trace?: never
    }
    '/auth/refresh': {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        get?: never
        put?: never
        /**
         * Обновление access-токена по refresh-токену из cookie
         * @description Тело не требуется. Refresh-токен передаётся в HttpOnly cookie.
         */
        post: {
            parameters: {
                query?: never
                header?: never
                path?: never
                cookie?: never
            }
            requestBody?: never
            responses: {
                /** @description Новый access-токен и sessionId */
                200: {
                    headers: {
                        [name: string]: unknown
                    }
                    content: {
                        'application/json': components['schemas']['AuthRefreshResponse']
                    }
                }
                401: components['responses']['ApiError401']
                500: components['responses']['ApiError500']
            }
        }
        delete?: never
        options?: never
        head?: never
        patch?: never
        trace?: never
    }
    '/auth/logout': {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        get?: never
        put?: never
        /**
         * Выход из текущей сессии
         * @description Ревокация refresh-сессии по cookie. Тело не требуется.
         */
        post: {
            parameters: {
                query?: never
                header?: never
                path?: never
                cookie?: never
            }
            requestBody?: never
            responses: {
                /** @description Успешный выход */
                204: {
                    headers: {
                        [name: string]: unknown
                    }
                    content?: never
                }
                500: components['responses']['ApiError500']
            }
        }
        delete?: never
        options?: never
        head?: never
        patch?: never
        trace?: never
    }
    '/auth/sessions': {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        /** Список активных сессий пользователя */
        get: {
            parameters: {
                query?: never
                header?: never
                path?: never
                cookie?: never
            }
            requestBody?: never
            responses: {
                /** @description Список сессий */
                200: {
                    headers: {
                        [name: string]: unknown
                    }
                    content: {
                        'application/json': components['schemas']['SessionInfo'][]
                    }
                }
                401: components['responses']['ApiError401']
                500: components['responses']['ApiError500']
            }
        }
        put?: never
        post?: never
        /**
         * Завершить все сессии кроме текущей
         * @description Текущая сессия определяется по refresh-cookie. Тело не требуется.
         */
        delete: {
            parameters: {
                query?: never
                header?: never
                path?: never
                cookie?: never
            }
            requestBody?: never
            responses: {
                /** @description Успешно */
                204: {
                    headers: {
                        [name: string]: unknown
                    }
                    content?: never
                }
                401: components['responses']['ApiError401']
                500: components['responses']['ApiError500']
            }
        }
        options?: never
        head?: never
        patch?: never
        trace?: never
    }
    '/auth/sessions/{sessionId}': {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        get?: never
        put?: never
        post?: never
        /** Отозвать конкретную сессию */
        delete: {
            parameters: {
                query?: never
                header?: never
                path: {
                    /** @description Идентификатор сессии для отзыва */
                    sessionId: components['parameters']['sessionId']
                }
                cookie?: never
            }
            requestBody?: never
            responses: {
                /** @description Сессия отозвана */
                204: {
                    headers: {
                        [name: string]: unknown
                    }
                    content?: never
                }
                401: components['responses']['ApiError401']
                403: components['responses']['ApiError403']
                404: components['responses']['ApiError404']
                500: components['responses']['ApiError500']
            }
        }
        options?: never
        head?: never
        patch?: never
        trace?: never
    }
    '/auth/change-password': {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        get?: never
        put?: never
        /** Смена пароля */
        post: {
            parameters: {
                query?: never
                header?: never
                path?: never
                cookie?: never
            }
            requestBody: {
                content: {
                    'application/json': components['schemas']['AuthChangePasswordRequest']
                }
            }
            responses: {
                /** @description Пароль изменён, возвращаются новые токены */
                200: {
                    headers: {
                        [name: string]: unknown
                    }
                    content: {
                        'application/json': components['schemas']['AuthChangePasswordResponse']
                    }
                }
                400: components['responses']['ApiError400']
                401: components['responses']['ApiError401']
                500: components['responses']['ApiError500']
            }
        }
        delete?: never
        options?: never
        head?: never
        patch?: never
        trace?: never
    }
    '/auth/confirm-email': {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        get?: never
        put?: never
        /** Подтверждение email по токену из письма */
        post: {
            parameters: {
                query?: never
                header?: never
                path?: never
                cookie?: never
            }
            requestBody: {
                content: {
                    'application/json': components['schemas']['AuthConfirmEmailRequest']
                }
            }
            responses: {
                /** @description Email подтверждён */
                204: {
                    headers: {
                        [name: string]: unknown
                    }
                    content?: never
                }
                400: components['responses']['ApiError400']
                500: components['responses']['ApiError500']
            }
        }
        delete?: never
        options?: never
        head?: never
        patch?: never
        trace?: never
    }
    '/auth/resend-confirm-email': {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        get?: never
        put?: never
        /**
         * Повторная отправка письма с подтверждением email
         * @description Требуется авторизация. Не чаще одного раза в 60 секунд на пользователя.
         */
        post: {
            parameters: {
                query?: never
                header?: never
                path?: never
                cookie?: never
            }
            requestBody?: never
            responses: {
                /** @description Письмо отправлено */
                204: {
                    headers: {
                        [name: string]: unknown
                    }
                    content?: never
                }
                400: components['responses']['ApiError400']
                401: components['responses']['ApiError401']
                /** @description Слишком частый запрос, повторите позже (retryAfter в error тела ответа) */
                429: {
                    headers: {
                        [name: string]: unknown
                    }
                    content: {
                        'application/json': {
                            error?: {
                                code?: string
                                message?: string
                                retryAfter?: number
                            }
                        }
                    }
                }
                500: components['responses']['ApiError500']
            }
        }
        delete?: never
        options?: never
        head?: never
        patch?: never
        trace?: never
    }
    '/users': {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        /** Список всех пользователей */
        get: {
            parameters: {
                query?: never
                header?: never
                path?: never
                cookie?: never
            }
            requestBody?: never
            responses: {
                /** @description Список пользователей */
                200: {
                    headers: {
                        [name: string]: unknown
                    }
                    content: {
                        'application/json': components['schemas']['User'][]
                    }
                }
                401: components['responses']['ApiError401']
                500: components['responses']['ApiError500']
            }
        }
        put?: never
        /** Создать пользователя */
        post: {
            parameters: {
                query?: never
                header?: never
                path?: never
                cookie?: never
            }
            requestBody: {
                content: {
                    'application/json': components['schemas']['UserCreate']
                }
            }
            responses: {
                /** @description Пользователь создан */
                201: {
                    headers: {
                        [name: string]: unknown
                    }
                    content: {
                        'application/json': components['schemas']['User']
                    }
                }
                400: components['responses']['ApiError400']
                401: components['responses']['ApiError401']
                500: components['responses']['ApiError500']
            }
        }
        delete?: never
        options?: never
        head?: never
        patch?: never
        trace?: never
    }
    '/users/me': {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        /**
         * Текущий пользователь
         * @description Возвращает данные авторизованного пользователя (в т.ч. emailConfirmedAt). Требуется access-токен.
         */
        get: {
            parameters: {
                query?: never
                header?: never
                path?: never
                cookie?: never
            }
            requestBody?: never
            responses: {
                /** @description Текущий пользователь */
                200: {
                    headers: {
                        [name: string]: unknown
                    }
                    content: {
                        'application/json': components['schemas']['User']
                    }
                }
                401: components['responses']['ApiError401']
                404: components['responses']['ApiError404']
                500: components['responses']['ApiError500']
            }
        }
        put?: never
        post?: never
        delete?: never
        options?: never
        head?: never
        patch?: never
        trace?: never
    }
    '/users/{id}': {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        /** Получить пользователя по ID */
        get: {
            parameters: {
                query?: never
                header?: never
                path: {
                    /** @description UUID сущности */
                    id: components['parameters']['id']
                }
                cookie?: never
            }
            requestBody?: never
            responses: {
                /** @description Пользователь */
                200: {
                    headers: {
                        [name: string]: unknown
                    }
                    content: {
                        'application/json': components['schemas']['User']
                    }
                }
                401: components['responses']['ApiError401']
                404: components['responses']['ApiError404']
                500: components['responses']['ApiError500']
            }
        }
        put?: never
        post?: never
        /** Удалить пользователя */
        delete: {
            parameters: {
                query?: never
                header?: never
                path: {
                    /** @description UUID сущности */
                    id: components['parameters']['id']
                }
                cookie?: never
            }
            requestBody?: never
            responses: {
                /** @description Пользователь удалён */
                204: {
                    headers: {
                        [name: string]: unknown
                    }
                    content?: never
                }
                401: components['responses']['ApiError401']
                404: components['responses']['ApiError404']
                500: components['responses']['ApiError500']
            }
        }
        options?: never
        head?: never
        /** Обновить пользователя */
        patch: {
            parameters: {
                query?: never
                header?: never
                path: {
                    /** @description UUID сущности */
                    id: components['parameters']['id']
                }
                cookie?: never
            }
            requestBody?: {
                content: {
                    'application/json': components['schemas']['UserUpdate']
                }
            }
            responses: {
                /** @description Обновлённый пользователь */
                200: {
                    headers: {
                        [name: string]: unknown
                    }
                    content: {
                        'application/json': components['schemas']['User']
                    }
                }
                400: components['responses']['ApiError400']
                401: components['responses']['ApiError401']
                404: components['responses']['ApiError404']
                500: components['responses']['ApiError500']
            }
        }
        trace?: never
    }
    '/budgets': {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        /** Список бюджетов текущего пользователя */
        get: {
            parameters: {
                query?: never
                header?: never
                path?: never
                cookie?: never
            }
            requestBody?: never
            responses: {
                /** @description Список бюджетов. Каждый объект содержит поле `role` — роль текущего пользователя в этом бюджете. */
                200: {
                    headers: {
                        [name: string]: unknown
                    }
                    content: {
                        'application/json': components['schemas']['BudgetListItem'][]
                    }
                }
                401: components['responses']['ApiError401']
                500: components['responses']['ApiError500']
            }
        }
        put?: never
        /** Создать бюджет */
        post: {
            parameters: {
                query?: never
                header?: never
                path?: never
                cookie?: never
            }
            requestBody: {
                content: {
                    'application/json': components['schemas']['BudgetCreate']
                }
            }
            responses: {
                /** @description Бюджет создан */
                201: {
                    headers: {
                        [name: string]: unknown
                    }
                    content: {
                        'application/json': components['schemas']['Budget']
                    }
                }
                400: components['responses']['ApiError400']
                401: components['responses']['ApiError401']
                500: components['responses']['ApiError500']
            }
        }
        delete?: never
        options?: never
        head?: never
        patch?: never
        trace?: never
    }
    '/budgets/{id}': {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        /** Получить бюджет по ID */
        get: {
            parameters: {
                query?: never
                header?: never
                path: {
                    /** @description UUID сущности */
                    id: components['parameters']['id']
                }
                cookie?: never
            }
            requestBody?: never
            responses: {
                /** @description Бюджет с ролью текущего пользователя */
                200: {
                    headers: {
                        [name: string]: unknown
                    }
                    content: {
                        'application/json': components['schemas']['BudgetListItem']
                    }
                }
                401: components['responses']['ApiError401']
                403: components['responses']['ApiError403']
                404: components['responses']['ApiError404']
                500: components['responses']['ApiError500']
            }
        }
        put?: never
        post?: never
        /** Удалить бюджет */
        delete: {
            parameters: {
                query?: never
                header?: never
                path: {
                    /** @description UUID сущности */
                    id: components['parameters']['id']
                }
                cookie?: never
            }
            requestBody?: never
            responses: {
                /** @description Бюджет удалён */
                204: {
                    headers: {
                        [name: string]: unknown
                    }
                    content?: never
                }
                401: components['responses']['ApiError401']
                403: components['responses']['ApiError403']
                404: components['responses']['ApiError404']
                500: components['responses']['ApiError500']
            }
        }
        options?: never
        head?: never
        /** Обновить бюджет */
        patch: {
            parameters: {
                query?: never
                header?: never
                path: {
                    /** @description UUID сущности */
                    id: components['parameters']['id']
                }
                cookie?: never
            }
            requestBody?: {
                content: {
                    'application/json': components['schemas']['BudgetUpdate']
                }
            }
            responses: {
                /** @description Обновлённый бюджет */
                200: {
                    headers: {
                        [name: string]: unknown
                    }
                    content: {
                        'application/json': components['schemas']['Budget']
                    }
                }
                400: components['responses']['ApiError400']
                401: components['responses']['ApiError401']
                403: components['responses']['ApiError403']
                404: components['responses']['ApiError404']
                500: components['responses']['ApiError500']
            }
        }
        trace?: never
    }
    '/accounts': {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        /** Список счетов */
        get: {
            parameters: {
                query?: never
                header?: never
                path?: never
                cookie?: never
            }
            requestBody?: never
            responses: {
                /** @description Список счетов */
                200: {
                    headers: {
                        [name: string]: unknown
                    }
                    content: {
                        'application/json': components['schemas']['Account'][]
                    }
                }
                401: components['responses']['ApiError401']
                500: components['responses']['ApiError500']
            }
        }
        put?: never
        /** Создать счёт */
        post: {
            parameters: {
                query?: never
                header?: never
                path?: never
                cookie?: never
            }
            requestBody: {
                content: {
                    'application/json': components['schemas']['AccountCreate']
                }
            }
            responses: {
                /** @description Счёт создан */
                201: {
                    headers: {
                        [name: string]: unknown
                    }
                    content: {
                        'application/json': components['schemas']['Account']
                    }
                }
                400: components['responses']['ApiError400']
                401: components['responses']['ApiError401']
                500: components['responses']['ApiError500']
            }
        }
        delete?: never
        options?: never
        head?: never
        patch?: never
        trace?: never
    }
    '/accounts/{id}': {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        /** Получить счёт по ID */
        get: {
            parameters: {
                query?: never
                header?: never
                path: {
                    /** @description UUID сущности */
                    id: components['parameters']['id']
                }
                cookie?: never
            }
            requestBody?: never
            responses: {
                /** @description Счёт */
                200: {
                    headers: {
                        [name: string]: unknown
                    }
                    content: {
                        'application/json': components['schemas']['Account']
                    }
                }
                401: components['responses']['ApiError401']
                404: components['responses']['ApiError404']
                500: components['responses']['ApiError500']
            }
        }
        put?: never
        post?: never
        /** Удалить счёт */
        delete: {
            parameters: {
                query?: never
                header?: never
                path: {
                    /** @description UUID сущности */
                    id: components['parameters']['id']
                }
                cookie?: never
            }
            requestBody?: never
            responses: {
                /** @description Счёт удалён */
                204: {
                    headers: {
                        [name: string]: unknown
                    }
                    content?: never
                }
                401: components['responses']['ApiError401']
                404: components['responses']['ApiError404']
                500: components['responses']['ApiError500']
            }
        }
        options?: never
        head?: never
        /** Обновить счёт */
        patch: {
            parameters: {
                query?: never
                header?: never
                path: {
                    /** @description UUID сущности */
                    id: components['parameters']['id']
                }
                cookie?: never
            }
            requestBody?: {
                content: {
                    'application/json': components['schemas']['AccountUpdate']
                }
            }
            responses: {
                /** @description Обновлённый счёт */
                200: {
                    headers: {
                        [name: string]: unknown
                    }
                    content: {
                        'application/json': components['schemas']['Account']
                    }
                }
                400: components['responses']['ApiError400']
                401: components['responses']['ApiError401']
                404: components['responses']['ApiError404']
                500: components['responses']['ApiError500']
            }
        }
        trace?: never
    }
    '/categories': {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        /** Список категорий */
        get: {
            parameters: {
                query?: never
                header?: never
                path?: never
                cookie?: never
            }
            requestBody?: never
            responses: {
                /** @description Список категорий */
                200: {
                    headers: {
                        [name: string]: unknown
                    }
                    content: {
                        'application/json': components['schemas']['Category'][]
                    }
                }
                401: components['responses']['ApiError401']
                500: components['responses']['ApiError500']
            }
        }
        put?: never
        /** Создать категорию */
        post: {
            parameters: {
                query?: never
                header?: never
                path?: never
                cookie?: never
            }
            requestBody: {
                content: {
                    'application/json': components['schemas']['CategoryCreate']
                }
            }
            responses: {
                /** @description Категория создана */
                201: {
                    headers: {
                        [name: string]: unknown
                    }
                    content: {
                        'application/json': components['schemas']['Category']
                    }
                }
                400: components['responses']['ApiError400']
                401: components['responses']['ApiError401']
                500: components['responses']['ApiError500']
            }
        }
        delete?: never
        options?: never
        head?: never
        patch?: never
        trace?: never
    }
    '/categories/{id}': {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        /** Получить категорию по ID */
        get: {
            parameters: {
                query?: never
                header?: never
                path: {
                    /** @description UUID сущности */
                    id: components['parameters']['id']
                }
                cookie?: never
            }
            requestBody?: never
            responses: {
                /** @description Категория */
                200: {
                    headers: {
                        [name: string]: unknown
                    }
                    content: {
                        'application/json': components['schemas']['Category']
                    }
                }
                401: components['responses']['ApiError401']
                404: components['responses']['ApiError404']
                500: components['responses']['ApiError500']
            }
        }
        put?: never
        post?: never
        /** Удалить категорию */
        delete: {
            parameters: {
                query?: never
                header?: never
                path: {
                    /** @description UUID сущности */
                    id: components['parameters']['id']
                }
                cookie?: never
            }
            requestBody?: never
            responses: {
                /** @description Категория удалена */
                204: {
                    headers: {
                        [name: string]: unknown
                    }
                    content?: never
                }
                401: components['responses']['ApiError401']
                404: components['responses']['ApiError404']
                500: components['responses']['ApiError500']
            }
        }
        options?: never
        head?: never
        /** Обновить категорию */
        patch: {
            parameters: {
                query?: never
                header?: never
                path: {
                    /** @description UUID сущности */
                    id: components['parameters']['id']
                }
                cookie?: never
            }
            requestBody?: {
                content: {
                    'application/json': components['schemas']['CategoryUpdate']
                }
            }
            responses: {
                /** @description Обновлённая категория */
                200: {
                    headers: {
                        [name: string]: unknown
                    }
                    content: {
                        'application/json': components['schemas']['Category']
                    }
                }
                400: components['responses']['ApiError400']
                401: components['responses']['ApiError401']
                404: components['responses']['ApiError404']
                500: components['responses']['ApiError500']
            }
        }
        trace?: never
    }
    '/transactions': {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        /** Список транзакций */
        get: {
            parameters: {
                query?: never
                header?: never
                path?: never
                cookie?: never
            }
            requestBody?: never
            responses: {
                /** @description Список транзакций */
                200: {
                    headers: {
                        [name: string]: unknown
                    }
                    content: {
                        'application/json': components['schemas']['Transaction'][]
                    }
                }
                401: components['responses']['ApiError401']
                500: components['responses']['ApiError500']
            }
        }
        put?: never
        /** Создать транзакцию */
        post: {
            parameters: {
                query?: never
                header?: never
                path?: never
                cookie?: never
            }
            requestBody: {
                content: {
                    'application/json': components['schemas']['TransactionCreate']
                }
            }
            responses: {
                /** @description Транзакция создана */
                201: {
                    headers: {
                        [name: string]: unknown
                    }
                    content: {
                        'application/json': components['schemas']['Transaction']
                    }
                }
                400: components['responses']['ApiError400']
                401: components['responses']['ApiError401']
                500: components['responses']['ApiError500']
            }
        }
        delete?: never
        options?: never
        head?: never
        patch?: never
        trace?: never
    }
    '/transactions/{id}': {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        /** Получить транзакцию по ID */
        get: {
            parameters: {
                query?: never
                header?: never
                path: {
                    /** @description UUID сущности */
                    id: components['parameters']['id']
                }
                cookie?: never
            }
            requestBody?: never
            responses: {
                /** @description Транзакция */
                200: {
                    headers: {
                        [name: string]: unknown
                    }
                    content: {
                        'application/json': components['schemas']['Transaction']
                    }
                }
                401: components['responses']['ApiError401']
                404: components['responses']['ApiError404']
                500: components['responses']['ApiError500']
            }
        }
        put?: never
        post?: never
        /** Удалить транзакцию */
        delete: {
            parameters: {
                query?: never
                header?: never
                path: {
                    /** @description UUID сущности */
                    id: components['parameters']['id']
                }
                cookie?: never
            }
            requestBody?: never
            responses: {
                /** @description Транзакция удалена */
                204: {
                    headers: {
                        [name: string]: unknown
                    }
                    content?: never
                }
                401: components['responses']['ApiError401']
                404: components['responses']['ApiError404']
                500: components['responses']['ApiError500']
            }
        }
        options?: never
        head?: never
        /** Обновить транзакцию */
        patch: {
            parameters: {
                query?: never
                header?: never
                path: {
                    /** @description UUID сущности */
                    id: components['parameters']['id']
                }
                cookie?: never
            }
            requestBody?: {
                content: {
                    'application/json': components['schemas']['TransactionUpdate']
                }
            }
            responses: {
                /** @description Обновлённая транзакция */
                200: {
                    headers: {
                        [name: string]: unknown
                    }
                    content: {
                        'application/json': components['schemas']['Transaction']
                    }
                }
                400: components['responses']['ApiError400']
                401: components['responses']['ApiError401']
                404: components['responses']['ApiError404']
                500: components['responses']['ApiError500']
            }
        }
        trace?: never
    }
    '/budget-members': {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        /** Список участников бюджета */
        get: {
            parameters: {
                query: {
                    /** @description ID бюджета для фильтрации списка */
                    budgetId: components['parameters']['budgetIdQuery']
                }
                header?: never
                path?: never
                cookie?: never
            }
            requestBody?: never
            responses: {
                /** @description Список участников */
                200: {
                    headers: {
                        [name: string]: unknown
                    }
                    content: {
                        'application/json': components['schemas']['BudgetMember'][]
                    }
                }
                401: components['responses']['ApiError401']
                403: components['responses']['ApiError403']
                500: components['responses']['ApiError500']
            }
        }
        put?: never
        /** Добавить участника в бюджет */
        post: {
            parameters: {
                query?: never
                header?: never
                path?: never
                cookie?: never
            }
            requestBody: {
                content: {
                    'application/json': components['schemas']['BudgetMemberCreate']
                }
            }
            responses: {
                /** @description Участник добавлен */
                201: {
                    headers: {
                        [name: string]: unknown
                    }
                    content: {
                        'application/json': components['schemas']['BudgetMember']
                    }
                }
                400: components['responses']['ApiError400']
                401: components['responses']['ApiError401']
                403: components['responses']['ApiError403']
                500: components['responses']['ApiError500']
            }
        }
        delete?: never
        options?: never
        head?: never
        patch?: never
        trace?: never
    }
    '/budget-members/{id}': {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        /** Получить участника по ID */
        get: {
            parameters: {
                query?: never
                header?: never
                path: {
                    /** @description UUID сущности */
                    id: components['parameters']['id']
                }
                cookie?: never
            }
            requestBody?: never
            responses: {
                /** @description Участник бюджета */
                200: {
                    headers: {
                        [name: string]: unknown
                    }
                    content: {
                        'application/json': components['schemas']['BudgetMember']
                    }
                }
                401: components['responses']['ApiError401']
                403: components['responses']['ApiError403']
                404: components['responses']['ApiError404']
                500: components['responses']['ApiError500']
            }
        }
        put?: never
        post?: never
        /** Удалить участника из бюджета */
        delete: {
            parameters: {
                query?: never
                header?: never
                path: {
                    /** @description UUID сущности */
                    id: components['parameters']['id']
                }
                cookie?: never
            }
            requestBody?: never
            responses: {
                /** @description Участник удалён */
                204: {
                    headers: {
                        [name: string]: unknown
                    }
                    content?: never
                }
                401: components['responses']['ApiError401']
                403: components['responses']['ApiError403']
                404: components['responses']['ApiError404']
                500: components['responses']['ApiError500']
            }
        }
        options?: never
        head?: never
        /** Обновить роль участника */
        patch: {
            parameters: {
                query?: never
                header?: never
                path: {
                    /** @description UUID сущности */
                    id: components['parameters']['id']
                }
                cookie?: never
            }
            requestBody?: {
                content: {
                    'application/json': components['schemas']['BudgetMemberUpdate']
                }
            }
            responses: {
                /** @description Обновлённый участник */
                200: {
                    headers: {
                        [name: string]: unknown
                    }
                    content: {
                        'application/json': components['schemas']['BudgetMember']
                    }
                }
                400: components['responses']['ApiError400']
                401: components['responses']['ApiError401']
                403: components['responses']['ApiError403']
                404: components['responses']['ApiError404']
                500: components['responses']['ApiError500']
            }
        }
        trace?: never
    }
    '/budget-invitations': {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        /** Список приглашений в бюджет */
        get: {
            parameters: {
                query: {
                    /** @description ID бюджета для фильтрации списка */
                    budgetId: components['parameters']['budgetIdQuery']
                }
                header?: never
                path?: never
                cookie?: never
            }
            requestBody?: never
            responses: {
                /** @description Список приглашений */
                200: {
                    headers: {
                        [name: string]: unknown
                    }
                    content: {
                        'application/json': components['schemas']['BudgetInvitation'][]
                    }
                }
                401: components['responses']['ApiError401']
                403: components['responses']['ApiError403']
                500: components['responses']['ApiError500']
            }
        }
        put?: never
        /** Создать приглашение в бюджет */
        post: {
            parameters: {
                query?: never
                header?: never
                path?: never
                cookie?: never
            }
            requestBody: {
                content: {
                    'application/json': components['schemas']['BudgetInvitationCreate']
                }
            }
            responses: {
                /** @description Приглашение создано */
                201: {
                    headers: {
                        [name: string]: unknown
                    }
                    content: {
                        'application/json': components['schemas']['BudgetInvitation']
                    }
                }
                400: components['responses']['ApiError400']
                401: components['responses']['ApiError401']
                403: components['responses']['ApiError403']
                500: components['responses']['ApiError500']
            }
        }
        delete?: never
        options?: never
        head?: never
        patch?: never
        trace?: never
    }
    '/budget-invitations/by-token/{token}': {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        /**
         * Получить приглашение по externalToken из ссылки в письме
         * @description Не требует авторизации. Возвращает приглашение с вложенным budget.name. 403/404 при невалидном или истёкшем токене.
         */
        get: {
            parameters: {
                query?: never
                header?: never
                path: {
                    /** @description externalToken из ссылки в письме */
                    token: string
                }
                cookie?: never
            }
            requestBody?: never
            responses: {
                /** @description Приглашение с данными бюджета */
                200: {
                    headers: {
                        [name: string]: unknown
                    }
                    content: {
                        'application/json': components['schemas']['BudgetInvitationWithBudget']
                    }
                }
                403: components['responses']['ApiError403']
                404: components['responses']['ApiError404']
                500: components['responses']['ApiError500']
            }
        }
        put?: never
        post?: never
        delete?: never
        options?: never
        head?: never
        patch?: never
        trace?: never
    }
    '/budget-invitations/{id}': {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        /** Получить приглашение по ID */
        get: {
            parameters: {
                query?: never
                header?: never
                path: {
                    /** @description UUID сущности */
                    id: components['parameters']['id']
                }
                cookie?: never
            }
            requestBody?: never
            responses: {
                /** @description Приглашение */
                200: {
                    headers: {
                        [name: string]: unknown
                    }
                    content: {
                        'application/json': components['schemas']['BudgetInvitation']
                    }
                }
                401: components['responses']['ApiError401']
                403: components['responses']['ApiError403']
                404: components['responses']['ApiError404']
                500: components['responses']['ApiError500']
            }
        }
        put?: never
        post?: never
        /** Удалить приглашение */
        delete: {
            parameters: {
                query?: never
                header?: never
                path: {
                    /** @description UUID сущности */
                    id: components['parameters']['id']
                }
                cookie?: never
            }
            requestBody?: never
            responses: {
                /** @description Приглашение удалено */
                204: {
                    headers: {
                        [name: string]: unknown
                    }
                    content?: never
                }
                401: components['responses']['ApiError401']
                403: components['responses']['ApiError403']
                404: components['responses']['ApiError404']
                500: components['responses']['ApiError500']
            }
        }
        options?: never
        head?: never
        /** Обновить приглашение (роль/статус) */
        patch: {
            parameters: {
                query?: never
                header?: never
                path: {
                    /** @description UUID сущности */
                    id: components['parameters']['id']
                }
                cookie?: never
            }
            requestBody?: {
                content: {
                    'application/json': components['schemas']['BudgetInvitationUpdate']
                }
            }
            responses: {
                /** @description Обновлённое приглашение */
                200: {
                    headers: {
                        [name: string]: unknown
                    }
                    content: {
                        'application/json': components['schemas']['BudgetInvitation']
                    }
                }
                400: components['responses']['ApiError400']
                401: components['responses']['ApiError401']
                403: components['responses']['ApiError403']
                404: components['responses']['ApiError404']
                500: components['responses']['ApiError500']
            }
        }
        trace?: never
    }
    '/budget-invitations/{id}/accept': {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        get?: never
        put?: never
        /** Принять приглашение (id приглашения из by-token) */
        post: {
            parameters: {
                query?: never
                header?: never
                path: {
                    /** @description UUID сущности */
                    id: components['parameters']['id']
                }
                cookie?: never
            }
            requestBody?: {
                content: {
                    '*/*'?: never
                }
            }
            responses: {
                /** @description Приглашение принято */
                200: {
                    headers: {
                        [name: string]: unknown
                    }
                    content: {
                        'application/json': components['schemas']['AcceptInvitationResponse']
                    }
                }
                400: components['responses']['ApiError400']
                401: components['responses']['ApiError401']
                403: components['responses']['ApiError403']
                404: components['responses']['ApiError404']
                500: components['responses']['ApiError500']
            }
        }
        delete?: never
        options?: never
        head?: never
        patch?: never
        trace?: never
    }
    '/budget-invitations/{id}/reject': {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        get?: never
        put?: never
        /** Отклонить приглашение */
        post: {
            parameters: {
                query?: never
                header?: never
                path: {
                    /** @description UUID сущности */
                    id: components['parameters']['id']
                }
                cookie?: never
            }
            requestBody?: {
                content: {
                    '*/*'?: never
                }
            }
            responses: {
                /** @description Приглашение отклонено */
                200: {
                    headers: {
                        [name: string]: unknown
                    }
                    content: {
                        'application/json': {
                            ok?: boolean
                        }
                    }
                }
                401: components['responses']['ApiError401']
                404: components['responses']['ApiError404']
                500: components['responses']['ApiError500']
            }
        }
        delete?: never
        options?: never
        head?: never
        patch?: never
        trace?: never
    }
    '/monthly-plans': {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        /** Список месячных планов */
        get: {
            parameters: {
                query?: never
                header?: never
                path?: never
                cookie?: never
            }
            requestBody?: never
            responses: {
                /** @description Список планов */
                200: {
                    headers: {
                        [name: string]: unknown
                    }
                    content: {
                        'application/json': components['schemas']['MonthlyPlan'][]
                    }
                }
                401: components['responses']['ApiError401']
                500: components['responses']['ApiError500']
            }
        }
        put?: never
        /** Создать месячный план */
        post: {
            parameters: {
                query?: never
                header?: never
                path?: never
                cookie?: never
            }
            requestBody: {
                content: {
                    'application/json': components['schemas']['MonthlyPlanCreate']
                }
            }
            responses: {
                /** @description План создан */
                201: {
                    headers: {
                        [name: string]: unknown
                    }
                    content: {
                        'application/json': components['schemas']['MonthlyPlan']
                    }
                }
                400: components['responses']['ApiError400']
                401: components['responses']['ApiError401']
                500: components['responses']['ApiError500']
            }
        }
        delete?: never
        options?: never
        head?: never
        patch?: never
        trace?: never
    }
    '/monthly-plans/{id}': {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        /** Получить месячный план по ID */
        get: {
            parameters: {
                query?: never
                header?: never
                path: {
                    /** @description UUID сущности */
                    id: components['parameters']['id']
                }
                cookie?: never
            }
            requestBody?: never
            responses: {
                /** @description Месячный план */
                200: {
                    headers: {
                        [name: string]: unknown
                    }
                    content: {
                        'application/json': components['schemas']['MonthlyPlan']
                    }
                }
                401: components['responses']['ApiError401']
                404: components['responses']['ApiError404']
                500: components['responses']['ApiError500']
            }
        }
        put?: never
        post?: never
        /** Удалить месячный план */
        delete: {
            parameters: {
                query?: never
                header?: never
                path: {
                    /** @description UUID сущности */
                    id: components['parameters']['id']
                }
                cookie?: never
            }
            requestBody?: never
            responses: {
                /** @description План удалён */
                204: {
                    headers: {
                        [name: string]: unknown
                    }
                    content?: never
                }
                401: components['responses']['ApiError401']
                404: components['responses']['ApiError404']
                500: components['responses']['ApiError500']
            }
        }
        options?: never
        head?: never
        /** Обновить месячный план */
        patch: {
            parameters: {
                query?: never
                header?: never
                path: {
                    /** @description UUID сущности */
                    id: components['parameters']['id']
                }
                cookie?: never
            }
            requestBody?: {
                content: {
                    'application/json': components['schemas']['MonthlyPlanUpdate']
                }
            }
            responses: {
                /** @description Обновлённый план */
                200: {
                    headers: {
                        [name: string]: unknown
                    }
                    content: {
                        'application/json': components['schemas']['MonthlyPlan']
                    }
                }
                400: components['responses']['ApiError400']
                401: components['responses']['ApiError401']
                404: components['responses']['ApiError404']
                500: components['responses']['ApiError500']
            }
        }
        trace?: never
    }
    '/monthly-plan-items': {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        /** Список пунктов месячного плана */
        get: {
            parameters: {
                query?: never
                header?: never
                path?: never
                cookie?: never
            }
            requestBody?: never
            responses: {
                /** @description Список пунктов плана */
                200: {
                    headers: {
                        [name: string]: unknown
                    }
                    content: {
                        'application/json': components['schemas']['MonthlyPlanItem'][]
                    }
                }
                401: components['responses']['ApiError401']
                500: components['responses']['ApiError500']
            }
        }
        put?: never
        /** Создать пункт плана */
        post: {
            parameters: {
                query?: never
                header?: never
                path?: never
                cookie?: never
            }
            requestBody: {
                content: {
                    'application/json': components['schemas']['MonthlyPlanItemCreate']
                }
            }
            responses: {
                /** @description Пункт плана создан */
                201: {
                    headers: {
                        [name: string]: unknown
                    }
                    content: {
                        'application/json': components['schemas']['MonthlyPlanItem']
                    }
                }
                400: components['responses']['ApiError400']
                401: components['responses']['ApiError401']
                500: components['responses']['ApiError500']
            }
        }
        delete?: never
        options?: never
        head?: never
        patch?: never
        trace?: never
    }
    '/monthly-plan-items/{id}': {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        /** Получить пункт плана по ID */
        get: {
            parameters: {
                query?: never
                header?: never
                path: {
                    /** @description UUID сущности */
                    id: components['parameters']['id']
                }
                cookie?: never
            }
            requestBody?: never
            responses: {
                /** @description Пункт плана */
                200: {
                    headers: {
                        [name: string]: unknown
                    }
                    content: {
                        'application/json': components['schemas']['MonthlyPlanItem']
                    }
                }
                401: components['responses']['ApiError401']
                404: components['responses']['ApiError404']
                500: components['responses']['ApiError500']
            }
        }
        put?: never
        post?: never
        /** Удалить пункт плана */
        delete: {
            parameters: {
                query?: never
                header?: never
                path: {
                    /** @description UUID сущности */
                    id: components['parameters']['id']
                }
                cookie?: never
            }
            requestBody?: never
            responses: {
                /** @description Пункт плана удалён */
                204: {
                    headers: {
                        [name: string]: unknown
                    }
                    content?: never
                }
                401: components['responses']['ApiError401']
                404: components['responses']['ApiError404']
                500: components['responses']['ApiError500']
            }
        }
        options?: never
        head?: never
        /** Обновить пункт плана */
        patch: {
            parameters: {
                query?: never
                header?: never
                path: {
                    /** @description UUID сущности */
                    id: components['parameters']['id']
                }
                cookie?: never
            }
            requestBody?: {
                content: {
                    'application/json': components['schemas']['MonthlyPlanItemUpdate']
                }
            }
            responses: {
                /** @description Обновлённый пункт плана */
                200: {
                    headers: {
                        [name: string]: unknown
                    }
                    content: {
                        'application/json': components['schemas']['MonthlyPlanItem']
                    }
                }
                400: components['responses']['ApiError400']
                401: components['responses']['ApiError401']
                404: components['responses']['ApiError404']
                500: components['responses']['ApiError500']
            }
        }
        trace?: never
    }
}
export type webhooks = Record<string, never>
export interface components {
    schemas: {
        ApiError: {
            error: {
                /** @description Код ошибки (например NOT_FOUND, BAD_REQUEST) */
                code: string
                /** @description Сообщение об ошибке */
                message: string
            }
        }
        /** @enum {string} */
        BudgetMemberRole: 'owner' | 'editor' | 'viewer'
        /** @enum {string} */
        BudgetInvitationRole: 'editor' | 'viewer'
        /** @enum {string} */
        BudgetInvitationStatus: 'pending' | 'accepted' | 'rejected'
        /** @enum {string} */
        AccountType: 'account' | 'card' | 'cash'
        /** @enum {string} */
        CategoryType: 'expense' | 'income' | 'transfer' | 'saving'
        /** @enum {string} */
        TransactionType: 'expense' | 'income' | 'transfer'
        User: {
            /** Format: uuid */
            id?: string
            /** Format: email */
            email?: string
            firstName?: string
            lastName?: string
            phone?: string | null
            telegram?: string | null
            /** Format: date-time */
            emailConfirmedAt?: string | null
            /** Format: date-time */
            createdAt?: string
            /** Format: date-time */
            updatedAt?: string
        }
        AuthUser: {
            /** Format: uuid */
            id?: string
            /** Format: email */
            email?: string
            firstName?: string
            lastName?: string
            /** Format: date-time */
            emailConfirmedAt?: string | null
        }
        Budget: {
            /** Format: uuid */
            id?: string
            name?: string
            currency?: string
            /** @description Денежная сумма в виде строки */
            initialBalance?: string
            /** Format: uuid */
            ownerId?: string
            /** Format: date-time */
            createdAt?: string
            /** Format: date-time */
            updatedAt?: string
        }
        BudgetListItem: components['schemas']['Budget'] & {
            role?: components['schemas']['BudgetMemberRole']
        }
        BudgetMember: {
            /** Format: uuid */
            id?: string
            role?: components['schemas']['BudgetMemberRole']
            /** Format: uuid */
            budgetId?: string
            /** Format: uuid */
            userId?: string
            User?: {
                /** Format: uuid */
                id?: string
                /** Format: email */
                email?: string
                firstName?: string
                lastName?: string
            }
            /** Format: date-time */
            createdAt?: string
            /** Format: date-time */
            updatedAt?: string
        }
        BudgetInvitation: {
            /** Format: uuid */
            id?: string
            /** Format: email */
            email?: string
            role?: components['schemas']['BudgetInvitationRole']
            status?: components['schemas']['BudgetInvitationStatus']
            /** Format: uuid */
            budgetId?: string
            /** Format: uuid */
            invitedById?: string | null
            /** Format: uuid */
            externalToken?: string
            /** Format: date-time */
            expiresAt?: string
            /** Format: date-time */
            createdAt?: string
            /** Format: date-time */
            updatedAt?: string
        }
        Account: {
            /** Format: uuid */
            id?: string
            name?: string
            type?: components['schemas']['AccountType']
            /** @description Денежная сумма в виде строки */
            initialBalance?: string
            /** @description Денежная сумма в виде строки */
            currentBalance?: string
            bank?: string | null
            /** Format: uuid */
            budgetId?: string
            /** Format: date-time */
            createdAt?: string
            /** Format: date-time */
            updatedAt?: string
            /** Format: date-time */
            deletedAt?: string | null
        }
        Category: {
            /** Format: uuid */
            id?: string
            name?: string
            type?: components['schemas']['CategoryType']
            /** Format: uuid */
            parentId?: string | null
            /** Format: uuid */
            budgetId?: string
            color?: string | null
            icon?: string | null
            /** Format: date-time */
            createdAt?: string
            /** Format: date-time */
            updatedAt?: string
            /** Format: date-time */
            deletedAt?: string | null
        }
        Transaction: {
            /** Format: uuid */
            id?: string
            type?: components['schemas']['TransactionType']
            /** @description Сумма в виде строки */
            amount?: string
            /** Format: date-time */
            occurredAt?: string
            description?: string | null
            /** Format: uuid */
            transferGroupId?: string | null
            /** Format: uuid */
            createdById?: string
            /** Format: uuid */
            updatedById?: string | null
            /** Format: uuid */
            budgetId?: string
            /**
             * Format: uuid
             * @description Счёт списания (расход, перевод)
             */
            debitAccountId?: string | null
            /**
             * Format: uuid
             * @description Счёт пополнения (доход, перевод)
             */
            creditAccountId?: string | null
            /** Format: uuid */
            categoryId?: string | null
            /** Format: date-time */
            createdAt?: string
            /** Format: date-time */
            updatedAt?: string
            /** Format: date-time */
            deletedAt?: string | null
        }
        MonthlyPlan: {
            /** Format: uuid */
            id?: string
            year?: number
            month?: number
            /** Format: uuid */
            budgetId?: string
            /** Format: date-time */
            createdAt?: string
            /** Format: date-time */
            updatedAt?: string
        }
        MonthlyPlanItem: {
            /** Format: uuid */
            id?: string
            plannedAmount?: string
            actualAmountSnapshot?: string | null
            /** Format: uuid */
            monthlyPlanId?: string
            /** Format: uuid */
            categoryId?: string
            /** Format: date-time */
            createdAt?: string
            /** Format: date-time */
            updatedAt?: string
        }
        SessionInfo: {
            /** Format: uuid */
            id?: string
            /** Format: date-time */
            createdAt?: string
            /** Format: date-time */
            lastUsedAt?: string | null
            userAgent?: string | null
            ip?: string | null
            /** Format: date-time */
            expiresAt?: string
        }
        AuthRegisterResponse: {
            accessToken?: string
            sessionId?: string
            user?: components['schemas']['AuthUser']
        }
        AuthLoginResponse: {
            accessToken?: string
            sessionId?: string
            user?: components['schemas']['AuthUser']
        }
        AuthRefreshResponse: {
            accessToken?: string
            sessionId?: string
        }
        AuthChangePasswordResponse: {
            accessToken?: string
            sessionId?: string
        }
        AuthRegisterRequest: {
            /** Format: email */
            email: string
            password: string
            firstName: string
            lastName: string
        }
        AuthLoginRequest: {
            /** Format: email */
            email: string
            password: string
        }
        AuthChangePasswordRequest: {
            currentPassword: string
            newPassword: string
        }
        AuthConfirmEmailRequest: {
            token: string
        }
        UserCreate: {
            /** Format: email */
            email: string
            password: string
            firstName: string
            lastName: string
        }
        UserUpdate: {
            firstName?: string
            lastName?: string
            phone?: string | null
            telegram?: string | null
        }
        BudgetCreate: {
            name: string
            currency: string
            /** @description Опционально */
            initialBalance?: string
        }
        BudgetUpdate: {
            name?: string
            currency?: string
            initialBalance?: string
        }
        BudgetMemberCreate: {
            /** Format: uuid */
            budgetId: string
            /** Format: uuid */
            userId: string
            role: components['schemas']['BudgetMemberRole']
        }
        BudgetMemberUpdate: {
            role: components['schemas']['BudgetMemberRole']
        }
        BudgetInvitationCreate: {
            /** Format: uuid */
            budgetId: string
            /** Format: email */
            email: string
            role: components['schemas']['BudgetInvitationRole']
        }
        BudgetInvitationUpdate: {
            role?: components['schemas']['BudgetInvitationRole']
            status?: components['schemas']['BudgetInvitationStatus']
        }
        AcceptInvitationResponse: {
            /** Format: uuid */
            budgetId?: string
            role?: components['schemas']['BudgetMemberRole']
        }
        BudgetInvitationWithBudget: components['schemas']['BudgetInvitation'] & {
            budget?: {
                name?: string
            }
        }
        AccountCreate: {
            name: string
            type: components['schemas']['AccountType']
            /** @description Опционально, по умолчанию 0 */
            initialBalance?: string
            bank?: string | null
            /** Format: uuid */
            budgetId: string
        }
        AccountUpdate: {
            name?: string
            type?: components['schemas']['AccountType']
            initialBalance?: string
            bank?: string | null
        }
        CategoryCreate: {
            name: string
            type: components['schemas']['CategoryType']
            /** Format: uuid */
            budgetId: string
            /** Format: uuid */
            parentId?: string | null
            color?: string | null
            icon?: string | null
        }
        CategoryUpdate: {
            name?: string
            type?: components['schemas']['CategoryType']
            /** Format: uuid */
            parentId?: string | null
            color?: string | null
            icon?: string | null
        }
        TransactionCreate: {
            type: components['schemas']['TransactionType']
            amount: string
            /** Format: date-time */
            occurredAt: string
            description?: string | null
            /** Format: uuid */
            transferGroupId?: string | null
            /** Format: uuid */
            budgetId: string
            /** Format: uuid */
            debitAccountId?: string | null
            /** Format: uuid */
            creditAccountId?: string | null
            /** Format: uuid */
            categoryId?: string | null
            /** Format: uuid */
            createdById: string
        }
        TransactionUpdate: {
            type?: components['schemas']['TransactionType']
            amount?: string
            /** Format: date-time */
            occurredAt?: string
            description?: string | null
            /** Format: uuid */
            debitAccountId?: string | null
            /** Format: uuid */
            creditAccountId?: string | null
            /** Format: uuid */
            categoryId?: string | null
            /** Format: uuid */
            updatedById?: string | null
        }
        MonthlyPlanCreate: {
            year: number
            month: number
            /** Format: uuid */
            budgetId: string
        }
        MonthlyPlanUpdate: {
            year?: number
            month?: number
        }
        MonthlyPlanItemCreate: {
            plannedAmount: string
            actualAmountSnapshot?: string | null
            /** Format: uuid */
            monthlyPlanId: string
            /** Format: uuid */
            categoryId: string
        }
        MonthlyPlanItemUpdate: {
            plannedAmount?: string
            actualAmountSnapshot?: string | null
            /** Format: uuid */
            categoryId?: string
        }
    }
    responses: {
        /** @description Bad request */
        ApiError400: {
            headers: {
                [name: string]: unknown
            }
            content: {
                'application/json': components['schemas']['ApiError']
            }
        }
        /** @description Unauthorized */
        ApiError401: {
            headers: {
                [name: string]: unknown
            }
            content: {
                'application/json': components['schemas']['ApiError']
            }
        }
        /** @description Forbidden */
        ApiError403: {
            headers: {
                [name: string]: unknown
            }
            content: {
                'application/json': components['schemas']['ApiError']
            }
        }
        /** @description Not found */
        ApiError404: {
            headers: {
                [name: string]: unknown
            }
            content: {
                'application/json': components['schemas']['ApiError']
            }
        }
        /** @description Conflict (e.g. email already in use) */
        ApiError409: {
            headers: {
                [name: string]: unknown
            }
            content: {
                'application/json': components['schemas']['ApiError']
            }
        }
        /** @description Internal server error */
        ApiError500: {
            headers: {
                [name: string]: unknown
            }
            content: {
                'application/json': components['schemas']['ApiError']
            }
        }
    }
    parameters: {
        /** @description UUID сущности */
        id: string
        /** @description Идентификатор сессии для отзыва */
        sessionId: string
        /** @description ID бюджета для фильтрации списка */
        budgetIdQuery: string
    }
    requestBodies: never
    headers: never
    pathItems: never
}
export type $defs = Record<string, never>
export type operations = Record<string, never>
